require('dotenv').config();
const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const auth = require('./routes/auth');
const cars = require('./routes/cars');
const reservations = require('./routes/reservations');
const users = require('./routes/users');
const app = express();
app.use(cors()); app.use(express.json());
const MONGO = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/carsdb';
mongoose.connect(MONGO).then(()=>console.log('MongoDB connected')).catch(e=>console.error(e));
app.use('/api/auth', auth);
app.use('/api/cars', cars);
app.use('/api/reservations', reservations);
app.use('/api/users', users);
app.get('/', (req,res)=>res.send({ok:true}));
const PORT = process.env.PORT || 5000;
app.listen(PORT, ()=>console.log('Server running on', PORT));
